---

# Which port should solr listen on
port: 8983

# Number of solr instances to run
replicaCount: 3

# Settings for solr java memory
javaMem: "-Xms2g -Xmx3g"

# Set the limits and requests on solr pod resources
resources: {}

# Solr image settings
image:
  repository: solr
  tag: 7.6.0
  pullPolicy: Always

# Solr pod liveness
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10

# Solr pod readiness
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5

# Annotations to apply to the solr pods
podAnnotations: {}

# Affinity group rules or the solr pods
affinity: {}

# Solr pod disruption budget
podDisruptionBudget:
  maxUnavailable: 1

# Configuration for the solr PVC
volumeClaimTemplates:
  storageSize: "20Gi"
  accessModes:
    - "ReadWriteOnce"

# Configuration for solr TLS handling, see README.md for more instructions
tls:
  enabled: false
  wantClientAuth: "false"
  needClientAuth: "false"
  keystorePassword: "changeit"
  importKubernetesCA: "false"
  checkPeerName: "false"
  caSecret:
    name: ""
    bundlePath: ""
  certSecret:
    name: ""
    keyPath: "key"
    certPath: "cert"


service:
  type: ClusterIP
  annotations: {}

# Configuration for the solr prometheus exporter
exporter:
  enabled: false # Deploy the exporter
  configFile: "/opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml" # The config file to point the exporter to
  updateStrategy: {}
  podAnnotations: {} # Annotations to apply to the exporter pod
  resources: {} # Resource limits for the exporter
  port: 9983 # The port to run the exporter on
  threads: 1 # The number of threads the exporter uses to query solr
  livenessProbe: # Liveness configuration for exporter pod
    initialDelaySeconds: 20
    periodSeconds: 10
  readinessProbe: # Readiness configuration for exporter pod
    initialDelaySeconds: 15
    periodSeconds: 5

# Override values for zookeeper subchart
zookeeper:
  replicaCount: 3
